export const POST_ARTICLE_UPLOAD = 'START_ARTICLE_UPLOAD';
export const SUCCESS_ARTICLE_UPLOAD = 'START_ARTICLE_UPLOAD';
export const WAIT_ARTICLE_UPLOAD = 'START_ARTICLE_UPLOAD';

export const START_UPLOAD_ARTICLE_POST_REQUEST = 'START_UPLOAD_ARTICLE_POST_REQUEST';
export const END_UPLOAD_ARTICLE_POST_REQUEST = 'END_UPLOAD_ARTICLE_POST_REQUEST';
